set (CMAKE_SYSTEM_NAME Linux)

set (CMAKE_C_COMPILER /usr/bin/gcc)
set (CMAKE_CXX_COMPILER /usr/bin/g++)

set (CMAKE_C_FLAGS "-m32" CACHE STRING "" FORCE)
set (CMAKE_CXX_FLAGS "-m32" CACHE STRING "" FORCE)
set (CMAKE_MODULE_LINKER_FLAGS "-m32" CACHE STRING "" FORCE)
